from Tkinter import*
c=Tk()
c.title("PYTHON PROJECT")
def fun():
    c.destroy()
    roo=Tk()
    roo.title("Project on Python")
    Label(roo,text="PROJECT TITLE: HOTEL BOOKING SYSTEM",font='times 30 bold',relief='ridge',bg='orange').grid(row=1,column=1)
    Label(roo,text="Name: Shivani Khare",font='times 30 bold',relief='ridge' ,bg='pink').grid(row=2,column=1)
    Label(roo,text="E.NO: 161B218",font='times 30 bold',relief='ridge' ,bg='yellow').grid(row=3,column=1)
    Label(roo,text="Branch: CSE,Year: II,Sem: III",font='times 30 bold',relief='ridge' ,bg='green').grid(row=4,column=1)
    def first():
        roo.destroy()
        root1=Tk()
        root1.title('Hotel Bookings')
        Label(root1,text='WELCOME TO HOTEL BOOKINGS',font='times 30 bold').pack()
        def fun():
            root1.destroy()
            root2=Tk()
            root2.title('Top Hotels::')
            Label(root2,text='STAYING OPTIONS',font='times 30 bold').pack()
            def bill1():
                root=Toplevel()
                
                root.title('Hotel Sara')
                root.geometry('500x500')
                Label(root,text='Select Your Room',font='times 20 bold',bg='Powder Blue').grid(row=0,column=1,columnspan=3)
                Label(root,text='(Bill Calculator)',font='times 15 bold',bg='yellow').grid(row=1,column=2)
                v1=IntVar()
                v2=IntVar()
                v3=IntVar()
                v4=IntVar()
                v5=IntVar()
                v6=IntVar()
                v7=IntVar()
                
                Checkbutton(root,text='AC Rooms(1500)',variable=v1,onvalue=1500,offvalue=0,bg='khaki').grid(row=2,column=0,sticky=W)
                Checkbutton(root,text='Non AC Rooms(800)',variable=v2,onvalue=800,offvalue=0,bg='grey').grid(row=3,column=0,sticky=W)
                Label(root,text='If food required',font='times 15 bold',bg='cyan').grid(row=4,column=2)
                Checkbutton(root,text='Breakfast(300)',variable=v3,onvalue=300,offvalue=0,bg='khaki').grid(row=5,column=0,sticky=W)
                Checkbutton(root,text='Lunch(500)',variable=v4,onvalue=500,offvalue=0,bg='grey').grid(row=6,column=0,sticky=W)
                Checkbutton(root,text='Dinner(500)',variable=v5,onvalue=500,offvalue=0,bg='khaki').grid(row=7,column=0,sticky=W)
                Label(root,text='                   ',).grid(row=8,column=0)
                Checkbutton(root,text='Banquet Hall(4000)',variable=v6,onvalue=4000,offvalue=0,bg='grey').grid(row=8,column=0,sticky=W)
                Checkbutton(root,text='Gym(100)',variable=v7,onvalue=100,offvalue=0,bg='khaki').grid(row=9,column=0,sticky=W)
                
                def total():
                    c=(int (v1.get())+int (v2.get())+int (v3.get())+int (v4.get())+int (v5.get())+int (v6.get())+int (v7.get()))
                    Label(root,text=('Total Amount to be paid : '+str(c))).grid()
                def close():
                    root.destroy()
                Button(root ,text='Bill Please',command=total,font='times 12 bold',bg='blue').grid(row=10,column=0,sticky=W)
                Button(root,text='EXIT',command=close,font='times 12 bold',bg='blue').grid(row=10,column=1,sticky=W)



                root.mainloop()
            def bill2():
                root3=Toplevel()
            
                root3.title('Hotel Varun')
                root3.geometry('500x500')
                Label(root3,text='Select Your Room',font='times 20 bold',bg='green').grid(row=0,column=1,columnspan=3)
                Label(root3,text='(Bill Calculator)',font='times 15 bold',bg='pink').grid(row=1,column=2)
                v1=IntVar()
                v2=IntVar()
                v3=IntVar()
                v4=IntVar()
                v5=IntVar()
                v6=IntVar()
                v7=IntVar()
                v8=IntVar()
                Checkbutton(root3,text='AC Rooms(1800)',variable=v1,onvalue=1800,offvalue=0,bg='grey').grid(row=2,column=0,sticky=W)
                Checkbutton(root3,text='Non AC Rooms(900)',variable=v2,onvalue=900,offvalue=0,bg='khaki',).grid(row=3,column=0,sticky=W)
                Label(root3,text='If food required',font='times 15 bold',bg='cyan').grid(row=4,column=2)
                Checkbutton(root3,text='Breakfast(200)',variable=v3,onvalue=200,offvalue=0,bg='grey').grid(row=5,column=0,sticky=W)
                Checkbutton(root3,text='Lunch(400)',variable=v4,onvalue=400,offvalue=0,bg='khaki').grid(row=6,column=0,sticky=W)
                Checkbutton(root3,text='Dinner(600)',variable=v5,onvalue=600,offvalue=0,bg='grey').grid(row=7,column=0,sticky=W)
                Label(root3,text='                   ',).grid(row=8,column=0)
                Checkbutton(root3,text='Banquet Hall(4000)',variable=v6,onvalue=4000,offvalue=0,bg='khaki').grid(row=8,column=0,sticky=W)
                Checkbutton(root3,text='Gym(100)',variable=v7,onvalue=100,offvalue=0,bg='grey').grid(row=9,column=0,sticky=W)
                Checkbutton(root3,text='Rooftop Hall(5000)',variable=v8,onvalue=5000,offvalue=0,bg='grey').grid(row=9,column=0,sticky=W)
                def total():
                    c=(int (v1.get())+int (v2.get())+int (v3.get())+int (v4.get())+int (v5.get())+int (v6.get())+int (v7.get())+int (v8.get()))
                    Label(root3,text=('Total Amount to be paid : '+str(c))).grid()
                def close():
                    root3.destroy()
                Button(root3 ,text='Bill Please',command=total,font='times 12 bold',bg='blue').grid(row=10,column=0,sticky=W)
                Button(root3,text='EXIT',command=close,font='times 12 bold',bg='blue').grid(row=10,column=1,sticky=W)

                root3.mainloop()

            def bill3():
                root4=Toplevel()
                
                root4.title('Hotel RajVilas')
                root4.geometry('500x500')
                Label(root4,text='Select Your Room',font='times 20 bold',bg='orange').grid(row=0,column=1,columnspan=3)
                Label(root4,text='(Bill Calculator)',font='times 15 bold',bg='purple').grid(row=1,column=2)
                v1=IntVar()
                v2=IntVar()
                v3=IntVar()
                v4=IntVar()
                v5=IntVar()
                v6=IntVar()
                v7=IntVar()
                v8=IntVar()
                v9=IntVar()
                Checkbutton(root4,text='AC Rooms(2000)',variable=v1,onvalue=2000,offvalue=0,bg='khaki').grid(row=2,column=0,sticky=W)
                Checkbutton(root4,text='Non AC Rooms(1000)',variable=v2,onvalue=1000,offvalue=0,bg='grey').grid(row=3,column=0,sticky=W)
                Label(root4,text='If food required',font='times 15 bold',bg='cyan').grid(row=4,column=2)
                Checkbutton(root4,text='Breakfast(300)',variable=v3,onvalue=300,offvalue=0,bg='khaki').grid(row=5,column=0,sticky=W)
                Checkbutton(root4,text='Lunch(500)',variable=v4,onvalue=500,offvalue=0,bg='grey').grid(row=6,column=0,sticky=W)
                Checkbutton(root4,text='Dinner(500)',variable=v5,onvalue=500,offvalue=0,bg='khaki').grid(row=7,column=0,sticky=W)
                Label(root4,text='                   ',).grid(row=8,column=0)
                Checkbutton(root4,text='Banquet Hall(6000)',variable=v6,onvalue=6000,offvalue=0,bg='grey').grid(row=8,column=0,sticky=W)
                Checkbutton(root4,text='Gym(500)',variable=v7,onvalue=500,offvalue=0,bg='khaki').grid(row=9,column=0,sticky=W)
                Checkbutton(root4,text='Rooftop Hall(8000)',variable=v8,onvalue=8000,offvalue=0,bg='khaki').grid(row=9,column=0,sticky=W)
                Checkbutton(root4,text='Swimming Pool(500)',variable=v9,onvalue=500,offvalue=0,bg='grey').grid(row=10,column=0,sticky=W)
                
                def total():
                    c=(int (v1.get())+int (v2.get())+int (v3.get())+int (v4.get())+int (v5.get())+int (v6.get())+int (v7.get())+int (v8.get())+int (v9.get()))
            
                    Label(root4,text=('Total Amount to be paid : '+str(c))).grid()
                def close():
                    root4.destroy()
                Button(root4 ,text='Bill Please',command=total,font='times 12 bold',bg='blue').grid(row=11,column=0,sticky=W)
                Button(root4,text='EXIT',command=close,font='times 12 bold',bg='blue').grid(row=11,column=1,sticky=W)

                root4.mainloop()
                
            def bill4():
                root5=Toplevel()
                root5.title('Hotel Vedantam')
                root5.geometry('500x500')
                Label(root5,text='Select Your Room',font='times 20 bold',bg='pink').grid(row=0,column=1,columnspan=3)
                Label(root5,text='(Bill Calculator)',font='times 15 bold',bg='pink').grid(row=1,column=2)
                v1=IntVar()
                v2=IntVar()
                v3=IntVar()
                v4=IntVar()
                v5=IntVar()
                v6=IntVar()
                v7=IntVar()
                v8=IntVar()
                v9=IntVar()
                v10=IntVar()
                Checkbutton(root5,text='AC Rooms(2000)',variable=v1,onvalue=1500,offvalue=0,bg='grey').grid(row=2,column=0,sticky=W)
                Checkbutton(root5,text='Non AC Rooms(1000)',variable=v2,onvalue=800,offvalue=0,bg='khaki').grid(row=3,column=0,sticky=W)
                Label(root5,text='If food required',font='times 15 bold',bg='cyan').grid(row=4,column=2)
                Checkbutton(root5,text='Breakfast(300)',variable=v3,onvalue=300,offvalue=0,bg='grey').grid(row=5,column=0,sticky=W)
                Checkbutton(root5,text='Lunch(500)',variable=v4,onvalue=500,offvalue=0,bg='khaki').grid(row=6,column=0,sticky=W)
                Checkbutton(root5,text='Dinner(500)',variable=v5,onvalue=500,offvalue=0,bg='grey').grid(row=7,column=0,sticky=W)
                Label(root5,text='                   ',).grid(row=8,column=0)
                Checkbutton(root5,text='Banquet Hall(6000)',variable=v6,onvalue=6000,offvalue=0,bg='khaki').grid(row=8,column=0,sticky=W)
                Checkbutton(root5,text='Gym(500)',variable=v7,onvalue=500,offvalue=0,bg='grey').grid(row=9,column=0,sticky=W)
                Checkbutton(root5,text='Rooftop Hall(8000)',variable=v8,onvalue=8000,offvalue=0,bg='khaki').grid(row=10,column=0,sticky=W)
                Checkbutton(root5,text='Swimming Pool(500)',variable=v9,onvalue=500,offvalue=0,bg='grey').grid(row=11,column=0,sticky=W)
                Checkbutton(root5,text='Spa&Salon(690)',variable=v10,onvalue=690,offvalue=0,bg='khaki').grid(row=12,column=0,sticky=W)
                
                def total():
                    c=(int (v1.get())+int (v2.get())+int (v3.get())+int (v4.get())+int (v5.get())+int (v6.get())+int (v7.get())+int (v8.get())+int (v9.get())+int (v10.get()))
                    Label(root5,text=('Total Amount to be paid : '+str(c))).grid(row=13,column=0,sticky=W)
                def close():
                    root5.destroy()
                Button(root5 ,text='Bill Please',command=total,font='times 12 bold',bg='blue').grid(row=14,column=0,sticky=W)
                Button(root5,text='EXIT',command=close,font='times 12 bold',bg='blue').grid(row=14,column=1,sticky=W)

                root5.mainloop()
            
            Button(root2,text='Hotel Sara',command=bill1,font='times 24 bold',width=15,height=3,bg='red').pack()
            Button(root2,text='Hotel Varun',command=bill2,font='times 24 bold',width=15,height=3,bg='yellow').pack()
            Button(root2,text='Hotel RajVilas',command=bill3,font='times 24 bold',width=15,height=3,bg='blue').pack()
            Button(root2,text='Hotel Vedantam',command=bill4,font='times 24 bold',width=15,height=3,bg='sea green').pack()
            root2.mainloop()
        Button(root1,text='AVAILABLE OPTIONS:',command=fun,width=18,height=2,bg='pink').pack()    
        root1.mainloop()
    Button(roo,text='GO',command=first,font='times 12 bold',bg='red',width=4,height=2).grid(row=5,column=1)
    roo.mainloop()
             
a=PhotoImage(file='proj.gif')
l=Label(c,image=a)
l.after(5000,fun)
l.pack()
c.mainloop()
